Declare @datefrom as datetime
set @datefrom = '2026/02/09'

-- DECLARE @StartOfYear DATE = DATEFROMPARTS(YEAR(@DATEFROM),1,1);
-- DECLARE @StartOfLastYear DATE = DATEADD(YEAR,-1,@StartOfYear);

-- ;WITH BaseData AS
-- (
--     SELECT
--         DET_STOCK_CODE,
--         DET_DATE,
--         DET_PERIODNUMBR,

--         -- 统一处理销售正负
--         CASE 
--             WHEN DET_TYPE = 'INV' THEN DET_NETT
--             WHEN DET_TYPE = 'CRN' THEN -DET_NETT
--         END AS SalesValue,

--         -- 统一处理成本正负
--         CASE 
--             WHEN DET_TYPE = 'INV' THEN DET_COSTPRICE * DET_QUANTITY
--             WHEN DET_TYPE = 'CRN' THEN -DET_COSTPRICE * DET_QUANTITY
--         END AS CostValue

--     FROM SL_PL_NL_DETAIL
--     WHERE 
--         DET_LEDGER = 'SL'
--         AND DET_TYPE IN ('INV','CRN')
--         AND DET_DATE >= @StartOfLastYear
--         AND DET_DATE <= @DATEFROM
-- )
-- SELECT
--     DET_STOCK_CODE,

--     -- ========= 本年 =========
--     SUM(CASE WHEN DET_DATE >= @StartOfYear 
--              AND DET_PERIODNUMBR = 1 THEN SalesValue END) AS Jan_Sales,

--     SUM(CASE WHEN DET_DATE >= @StartOfYear 
--              AND DET_PERIODNUMBR = 1 THEN CostValue END) AS Jan_COS,

--     SUM(CASE WHEN DET_DATE >= @StartOfYear 
--              AND DET_PERIODNUMBR = 2 THEN SalesValue END) AS Feb_Sales,

--     SUM(CASE WHEN DET_DATE >= @StartOfYear 
--              AND DET_PERIODNUMBR = 2 THEN CostValue END) AS Feb_COS,

--     -- ……一直写到 12 月（这里只展示模式）

--     -- ========= 去年 =========
--     SUM(CASE WHEN DET_DATE < @StartOfYear 
--              AND DET_PERIODNUMBR = 1 THEN SalesValue END) AS Jan_Sales_LY,

--     SUM(CASE WHEN DET_DATE < @StartOfYear 
--              AND DET_PERIODNUMBR = 1 THEN CostValue END) AS Jan_COS_LY

--     -- ……一直写到 12 月

-- FROM BaseData
-- GROUP BY DET_STOCK_CODE

-- HAVING 
--     SUM(SalesValue) <> 0
--     OR
--     SUM(CostValue) <> 0




-- return;




SELECT
dbo.STK_STOCK.STKCODE AS 'Stock Code',
dbo.STK_STOCK.STKNAME AS 'Description',
(CASE WHEN dbo.STK_STOCK3.STK_USRCHAR2 IS NULL THEN 'OTHERS'
      WHEN dbo.STK_STOCK3.STK_USRCHAR2 = '' THEN 'OTHERS'
      ELSE dbo.STK_STOCK3.STK_USRCHAR2
END) AS 'Business Type',
(CASE WHEN STK_SORT_KEY = '30 BOUCHARD' OR STK_SORT_KEY = '30 BOUCHARD DELISTED' THEN
		'30 IBA'
	ELSE
	STK_SORT_KEY
	END)  AS 'Sort Key',
dbo.STK_STOCK.STK_SORT_KEY1 AS 'User Key 1',
dbo.STK_STOCK.STK_SORT_KEY2 AS 'User Key 2',
dbo.STK_STOCK.STK_SORT_KEY3 AS 'User Key 3',	
dbo.STK_STOCK3.STK_USRFLAG3 AS 'Delisted',
dbo.STK_STOCK3.STK_USRCHAR16 AS 'Exec',
dbo.STK_STOCK3.STK_USRCHAR18 AS 'CategManager',
SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jan_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jan_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Feb_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Feb_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Mar_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Mar_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Apr_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Apr_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS May_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS May_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jun_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jun_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jul_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jul_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Aug_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Aug_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Sep_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Sep_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Oct_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Oct_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Nov_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Nov_COS,
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Dec_Sales,
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Dec_COS,
----Last Year
	SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jan_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jan_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Feb_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Feb_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Mar_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Mar_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Apr_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Apr_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS May_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS May_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jun_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jun_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jul_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Jul_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Aug_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Aug_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Sep_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Sep_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Oct_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Oct_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Nov_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Nov_COS_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Dec_Sales_LY,
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) AS Dec_COS_LY

    	

FROM         dbo.SL_PL_NL_DETAIL INNER JOIN
             dbo.STK_STOCK ON dbo.SL_PL_NL_DETAIL.DET_STOCK_CODE = dbo.STK_STOCK.STKCODE 
			 INNER JOIN dbo.STK_STOCK3 ON dbo.STK_STOCK.STKCODE = dbo.STK_STOCK3.STKCODE3
WHERE     DET_TYPE IN ('INV', 'CRN') AND DET_LEDGER = 'SL'
AND DET_DATE <= @DATEFROM
AND (dbo.SL_PL_NL_DETAIL.DET_STKSORTKEY3 not in  ('30 HERMES'))
AND (dbo.SL_PL_NL_DETAIL.DET_STKSORTKEY not in ('30 NATSEA'))
GROUP BY
(CASE WHEN dbo.STK_STOCK3.STK_USRCHAR2 IS NULL THEN 'OTHERS'
      WHEN dbo.STK_STOCK3.STK_USRCHAR2 = '' THEN 'OTHERS'
      ELSE dbo.STK_STOCK3.STK_USRCHAR2
END),
(CASE WHEN STK_SORT_KEY = '30 BOUCHARD' OR STK_SORT_KEY = '30 BOUCHARD DELISTED' THEN
		'30 IBA'
	ELSE
		STK_SORT_KEY
	END),
dbo.STK_STOCK.STK_SORT_KEY1, 
dbo.STK_STOCK.STK_SORT_KEY2,
dbo.STK_STOCK.STK_SORT_KEY3,
dbo.STK_STOCK.STKCODE,
dbo.STK_STOCK.STKNAME,
dbo.STK_STOCK3.STK_USRFLAG3,
dbo.STK_STOCK3.STK_USRCHAR16,
dbo.STK_STOCK3.STK_USRCHAR18
HAVING (SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM) THEN
             		(CASE WHEN DET_DATE <= @DATEFROM THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 1 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 2 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 3 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 4 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 5 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 6 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 7 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 8 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 9 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 10 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 11 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN DET_NETT * 1 
	        				WHEN 'CRN' THEN (DET_NETT * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END) +
SUM (CASE WHEN DET_PERIODNUMBR = 12 THEN
		(CASE WHEN YEAR(DET_DATE) = YEAR(@DATEFROM)-1 THEN
             		(CASE WHEN DET_DATE <= DATEADD(YYYY, -1, @DATEFROM) THEN
 				(CASE DET_TYPE WHEN 'INV' THEN (DET_COSTPRICE * DET_QUANTITY) * 1 
	        				WHEN 'CRN' THEN ((DET_COSTPRICE * DET_QUANTITY) * - 1)
         			END)
             		END)
		ELSE	
			0
		END)
	ELSE
		0 
	END)) <> 0

ORDER BY 'Business Type', 'Sort Key', 'User Key 1', 'User Key 2', 'User Key 3', 'Stock Code', 'Description', 'Exec', 'CategManager'