SELECT STKCODE StkCode, STKNAME AS StkName, STK_USRFLAG3 AS [Fridge Item]
FROM STK_STOCK S
INNER JOIN STK_STOCK3 S3 ON S.STKCODE=S3.STKCODE3
WHERE STK_DO_NOT_USE = 0 AND S3.STK_USRFLAG3 = 1
ORDER BY 2

SELECT STKCODE StkCode, STKNAME AS StkName, STK_USRCHAR2 AS [Classification]
FROM STK_STOCK S
INNER JOIN STK_STOCK3 S3 ON S.STKCODE=S3.STKCODE3
WHERE STK_DO_NOT_USE = 0 AND S3.STK_USRCHAR2 LIKE '%BIOTIC%'
ORDER BY 2