SELECT STKCODE AS 'Inventory ID', STKNAME AS 'Description',
STK_SORT_KEY1 AS 'Sort Key',
S.STK_SORT_KEY AS 'User Sort 1', STK_PHYSICAL AS StkQty
FROM STK_STOCK S
INNER JOIN STK_STOCK3 S3 ON S.STKCODE=S3.STKCODE3
INNER JOIN STK_STOCK_2 S2 ON S.STKCODE=S2.STKCODE2
INNER JOIN SL_ANALYSIS SL ON S2.STK_SANALYSIS1=SL.SACODE
INNER JOIN SYS_VATCONTROL V ON SL.SAVATCODE=V.VAT_CODE
INNER JOIN (SELECT DISTINCT LOC_STOCKCODE2, LOC_USERFLAG1, LOC_USERFLAG2 FROM STK_LOCATION2) L ON S.STKCODE=L.LOC_STOCKCODE2
WHERE S.STK_DO_NOT_USE=0