SELECT STK_SORT_KEY3 AS StkType, STKCODE AS StkCode, STKNAME AS StkName, STK_COSTPRICE AS CostPrice, 
STK_SELLPRICE1 AS Price1, STK_SELLPRICE2 AS Price2,
STK_SELLPRICE3 AS Price3, STK_SELLPRICE4 AS Price4, 
STK_SELLPRICE5 AS Price5, STK_SELLPRICE6 AS Price6, 
STK_SELLPRICE7 AS Price7, STK_SELLPRICE8 AS Price8, 
STK_SELLPRICE9 AS Price9, STK_SELLPRICE10 AS Price10,
V.VAT_RATE AS VAT_Rate
FROM STK_STOCK S
INNER JOIN STK_STOCK_2 S2 ON S.STKCODE=S2.STKCODE2
INNER JOIN SL_ANALYSIS A ON S2.STK_SANALYSIS10=A.SACODE
INNER JOIN SYS_VATCONTROL V ON A.SAVATCODE=V.VAT_CODE
WHERE STK_DO_NOT_USE = 0