use VJSCL;

DECLARE @stock NVARCHAR(50);
set @stock = '50ABBABBCATH14GX50';


-- select 
-- *
-- from dbo.STK_STOCK
-- where STKCODE like @stock
-- -- where STK_RTP_FLAG = 0
-- -- where STK_S_WEIGHT != 0
-- ;

-- 50ABBABBCATH14GX50,50ABBABBCATH14GX50T
select stk.* , stk2.*, stk3.*, stk4.*
from stk_stock as stk
    LEFT JOIN STK_STOCK_2 as stk2 ON stk.STKCODE = stk2.STKCODE2
    LEFT JOIN STK_STOCK3 as stk3 on stk.STKCODE = stk3.STKCODE3
    LEFT JOIN STK_STOCK4 as stk4 on stk.STKCODE = stk4.STKCODE4
where stkcode like @stock
;



-- SELECT *
-- FROM SL_ADDRESSES
-- WHERE AD_ACC_CODE LIKE '508till001';


select top(1000)CU_PRICE_KEY
from SL_ACCOUNTS;

select top(1000) 
STK_SANALYSIS1,
STK_SANALYSIS2,
STK_SANALYSIS3,
STK_SANALYSIS4,
STK_SANALYSIS5,
STK_SANALYSIS6,
STK_SANALYSIS7,
STK_SANALYSIS8,
STK_SANALYSIS9,
STK_SANALYSIS10,
* 
from vjscl.dbo.STK_STOCK_2

select sucode,su_import_code
from vjscl.dbo.pl_accounts
-- where sucode = '30aca001'


use VJSP;
SELECT 
    STK.STK_SORT_KEY AS 'Supplier',
    STK.STK_SORT_KEY1 AS 'Brand', 
    STK.STK_SORT_KEY3 AS 'Type', 
    STK.STKCODE AS 'Code', 
    STK.STKNAME AS 'Description', 
    STK.STK_PHYSICAL AS 'PhysicalStock', 
    SUM(CASE 
        WHEN DET.DET_TYPE = 'CRN' AND YEAR(DET.DET_DATE) = 2024 THEN DET.DET_NETT * -1
        WHEN DET.DET_TYPE <> 'CRN' AND YEAR(DET.DET_DATE) = 2024 THEN DET.DET_NETT
        ELSE 0
    END) AS 'Sales2024',
    SUM(CASE 
        WHEN DET.DET_TYPE = 'CRN' AND YEAR(DET.DET_DATE) = 2025 THEN DET.DET_NETT * -1
        WHEN DET.DET_TYPE <> 'CRN' AND YEAR(DET.DET_DATE) = 2025 THEN DET.DET_NETT
        ELSE 0
    END) AS 'Sales2025'
FROM [VJSP].[dbo].[STK_STOCK] STK
INNER JOIN [VJSP].[dbo].[SL_PL_NL_DETAIL] DET 
    ON STK.STKCODE = DET.DET_STOCK_CODE
WHERE 
    STK.STK_DO_NOT_USE = 0
    AND DET.DET_ORIGIN = 'SO'
GROUP BY 
    STK.STK_SORT_KEY,
    STK.STK_SORT_KEY1, 
    STK.STK_SORT_KEY3, 
    STK.STKCODE, 
    STK.STKNAME, 
    STK.STK_PHYSICAL
ORDER BY 1, 2, 3, 4;