SELECT CUCODE, CUNAME, CU_INV_LAYOUT_LINK, D.SDL_DOC_NAME
FROM SL_ACCOUNTS A
INNER JOIN [SYS_DOCUMENT_LAYOUTS] D ON A.CU_INV_LAYOUT_LINK=D.SDL_PRIMARY
WHERE CU_DO_NOT_USE = 0 AND CU_INV_LAYOUT_LINK IS NOT NULL AND CU_INV_LAYOUT_LINK != 0 AND CU_INV_LAYOUT_LINK != 1
 