DECLARE @ActiveCustomer TABLE (VALUE INT);

INSERT INTO
    @ActiveCustomer (VALUE)
VALUES
    (0),
    (1);

SELECT
    SL.CUCODE,
    SL.CUSORT,
    SL.CUNAME,
    SLA.AD_ADDRESS,
    SLA.AD_ADDRESS_USER1,
    SLA.AD_PHONE,
    CAST(SL.CU_DO_NOT_USE AS INT) AS CU_DO_NOT_USE
FROM
    SL_ACCOUNTS SL
    INNER JOIN SL_ADDRESSES SLA ON SL.CUCODE = SLA.AD_ACC_CODE AND
    SL.CU_DEL_ADD_CDE = SLA.AD_CODE
WHERE
    SL.CU_DO_NOT_USE IN (
        SELECT
            VALUE
        FROM
            @ActiveCustomer
    );