 SELECT "SL_TRANSACTIONS"."ST_COPYCUST", "SL_TRANSACTIONS"."ST_TRANTYPE", "SL_TRANSACTIONS"."ST_HEADER_REF", "SL_TRANSACTIONS"."ST_DATE", "SL_TRANSACTIONS"."ST_DUEDATE", "SL_TRANSACTIONS"."ST_GROSS", "SL_TRANSACTIONS"."ST_UNALLOCATED", "SL_ACCOUNTS"."CUNAME", "SL_ACCOUNTS"."CU_A_P_DAYS", "SL_TRANSACTIONS"."ST_USER1", "SL_ACCOUNTS"."CU_DUE_DAYS", "SL_ACCOUNTS2"."CU_USRFLAG6"
 FROM   ("SVBeauty"."dbo"."SL_TRANSACTIONS" "SL_TRANSACTIONS" INNER JOIN "SVBeauty"."dbo"."SL_ACCOUNTS" "SL_ACCOUNTS" ON "SL_TRANSACTIONS"."ST_COPYCUST"="SL_ACCOUNTS"."CUCODE") INNER JOIN "SVBeauty"."dbo"."SL_ACCOUNTS2" "SL_ACCOUNTS2" ON "SL_ACCOUNTS"."CUCODE"="SL_ACCOUNTS2"."CUCODE2"
 WHERE 
--   "SL_TRANSACTIONS"."ST_USER1"='20 NICOLA VB'   AND 
  "SL_TRANSACTIONS"."ST_UNALLOCATED"<>0 AND "SL_TRANSACTIONS"."ST_DATE"<{ts '2026-08-11 00:00:00'} AND ("SL_TRANSACTIONS"."ST_TRANTYPE"='ACR' OR "SL_TRANSACTIONS"."ST_TRANTYPE"='ADR' OR "SL_TRANSACTIONS"."ST_TRANTYPE"='CRN' OR "SL_TRANSACTIONS"."ST_TRANTYPE"='INV' OR "SL_TRANSACTIONS"."ST_TRANTYPE"='PAY') AND "SL_ACCOUNTS2"."CU_USRFLAG6"=0
 ORDER BY "SL_TRANSACTIONS"."ST_USER1", "SL_TRANSACTIONS"."ST_COPYCUST", "SL_TRANSACTIONS"."ST_DATE"


