-- Added by Paul 20260604_105520
-- Shift today's date back by 20 days to determine the reporting month.
-- This means dates from the 1st to the 20th are treated as the previous reporting month,
-- while dates from the 21st onward are treated as the current reporting month.
DECLARE @ReportDate DATE;
SET @ReportDate = DATEADD(DAY, -20, GETDATE());

---CTE QUERIES FOR NUMBER OF CUSTOMERS AND NET SALES
---TEMP TABLE ACANA DISTRIBUTION
SELECT DISTINCT
	DET_ACCOUNT INTO #ACADISTRIB
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
WHERE
	D.DET_ORIGIN = 'SO' AND
	YEAR(D.DET_DATE) = YEAR(@ReportDate) AND
	MONTH(D.DET_DATE) = MONTH(@ReportDate) AND
	S.STK_SORT_KEY = '30 ACANA PET'
	---TEMP TABLE ORIJEN DISTRIBUTION
SELECT DISTINCT
	DET_ACCOUNT INTO #ORIDISTRIB
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
WHERE
	D.DET_ORIGIN = 'SO' AND --YEAR(D.DET_DATE)=YEAR(GETDATE())
	YEAR(D.DET_DATE) = YEAR(@ReportDate) AND
	MONTH(D.DET_DATE) = MONTH(@ReportDate) AND
	S.STK_SORT_KEY = '30 ORIJEN'
	---TEMP TABLE ACANA CHEAP
SELECT DISTINCT
	DET_ACCOUNT INTO #ACANACHEAP
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
	INNER JOIN STK_STOCK3 S3 ON S.STKCODE = S3.STKCODE3
WHERE
	D.DET_ORIGIN = 'SO' AND --YEAR(D.DET_DATE)=YEAR(GETDATE())
	YEAR(D.DET_DATE) = YEAR(@ReportDate) AND
	MONTH(D.DET_DATE) = MONTH(@ReportDate) AND
	S.STK_SORT_KEY = '30 ACANA PET' AND
	STK_USRCHAR17 = 'Yes'
	---TEMP TABLE ORIJEN DOG SMALL BREED
SELECT DISTINCT
	DET_ACCOUNT INTO #ORIDOGSB
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
	INNER JOIN STK_STOCK3 S3 ON S.STKCODE = S3.STKCODE3
WHERE
	D.DET_ORIGIN = 'SO' AND --YEAR(D.DET_DATE)=YEAR(GETDATE())
	YEAR(D.DET_DATE) = YEAR(@ReportDate) AND
	MONTH(D.DET_DATE) = MONTH(@ReportDate) AND
	S.STK_SORT_KEY = '30 ORIJEN' AND
	STK_USRCHAR17 = 'Yes'
	---TEMP TABLE NET SALES
SELECT
	DET_ACCOUNT,
	SUM(
		CASE
			WHEN DET_TYPE = 'CRN' THEN DET_NETT * -1
			ELSE DET_NETT
		END
	) AS NET INTO #NETSALES
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
WHERE
	D.DET_ORIGIN = 'SO' AND --YEAR(D.DET_DATE)=YEAR(GETDATE()) AND MONTH(D.DET_DATE)=MONTH(GETDATE())
	YEAR(D.DET_DATE) = YEAR(@ReportDate) AND
	MONTH(D.DET_DATE) = MONTH(@ReportDate) AND
	S.STK_SORT_KEY3 = '30 CHAMPION PETFOODS'
GROUP BY
	DET_ACCOUNT
	--ROW 1 - CHAINS (ALL 0)
SELECT
	'1' AS [Order],
	'Pet Shop (Chains)' AS [Group],
	'Chain' AS [Type],
	0 AS [Total Relevant Numeric Distribution Points (# shops in market)],
	0 AS [ACANA Numeric Distribution (# shops ACANA)],
	0 AS [ORIJEN Numeric Distribution (# shops ORIJEN)],
	0 AS [# Shops New ACANA Cat in],
	0 AS [# Shops ORIJEN Small Breed in],
	0 AS [Rate of Sale (avg sell-out per store (local currency))],
	0 AS [Total Turnover per account (local currency)],
	'Royal Canin, Eukanuba, Hill''s S/P, Brit, Applaws (Cat), Taste of the Wild, N&D, Fisherman''s Daughter, Monge' AS [Competitive Benchmark brand's Distribution (which brands we should be targeting in same channel)]
UNION ALL
--ROW 2 - INDEPENDENT SHOPS
SELECT
	'2' AS [Order],
	'Pet Shop (Independent)',
	'Independent',
	COUNT(DISTINCT CUCODE),
	COUNT(DISTINCT AD.DET_ACCOUNT),
	COUNT(DISTINCT OD.DET_ACCOUNT),
	COUNT(DISTINCT AC.DET_ACCOUNT),
	COUNT(DISTINCT ODSB.DET_ACCOUNT),
	CASE
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN 0
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) != 0 THEN (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) != 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) > COUNT(DISTINCT OD.DET_ACCOUNT) THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		ELSE (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
	END,
	SUM(N.NET),
	'Royal Canin, Eukanuba, Hill''s S/P, Brit, Applaws (Cat), Taste of the Wild, N&D, Fisherman''s Daughter, Monge'
FROM
	SL_ACCOUNTS A
	INNER JOIN SL_ACCOUNTS2 A2 ON A.CUCODE = A2.CUCODE2
	LEFT JOIN #ACADISTRIB AD ON A.CUCODE = AD.DET_ACCOUNT
	LEFT JOIN #ORIDISTRIB OD ON A.CUCODE = OD.DET_ACCOUNT
	LEFT JOIN #ACANACHEAP AC ON A.CUCODE = AC.DET_ACCOUNT
	LEFT JOIN #ORIDOGSB ODSB ON A.CUCODE = ODSB.DET_ACCOUNT
	LEFT JOIN #NETSALES N ON A.CUCODE = N.DET_ACCOUNT
WHERE
	CU_DO_NOT_USE = 0 AND
	CUSORT IN ('30 PET A', '30 PET B', '30 PET C') AND
	A2.CU_USRCHAR16 != 'Yes'
UNION ALL
--ROW 3 - GROOMERS
SELECT
	'3' AS [Order],
	'Pet Shop (Independent)',
	'Groomers',
	COUNT(DISTINCT CUCODE),
	COUNT(DISTINCT AD.DET_ACCOUNT),
	COUNT(DISTINCT OD.DET_ACCOUNT),
	COUNT(DISTINCT AC.DET_ACCOUNT),
	COUNT(DISTINCT ODSB.DET_ACCOUNT),
	CASE
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN 0
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) != 0 THEN (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) != 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) > COUNT(DISTINCT OD.DET_ACCOUNT) THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		ELSE (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
	END,
	SUM(N.NET),
	'Royal Canin, Eukanuba, Hill''s S/P, Brit, Applaws (Cat), Taste of the Wild, N&D, Fisherman''s Daughter, Monge'
FROM
	SL_ACCOUNTS A
	INNER JOIN SL_ACCOUNTS2 A2 ON A.CUCODE = A2.CUCODE2
	LEFT JOIN #ACADISTRIB AD ON A.CUCODE = AD.DET_ACCOUNT
	LEFT JOIN #ORIDISTRIB OD ON A.CUCODE = OD.DET_ACCOUNT
	LEFT JOIN #ACANACHEAP AC ON A.CUCODE = AC.DET_ACCOUNT
	LEFT JOIN #ORIDOGSB ODSB ON A.CUCODE = ODSB.DET_ACCOUNT
	LEFT JOIN #NETSALES N ON A.CUCODE = N.DET_ACCOUNT
WHERE
	CU_DO_NOT_USE = 0 AND
	CUSORT = '30 GROOMER'
UNION ALL
--ROW 4 - BM AND ONLINE
SELECT
	'4' AS [Order],
	'Pet Shop (Independent)',
	'Other (B&M + Online)',
	COUNT(DISTINCT CUCODE),
	COUNT(DISTINCT AD.DET_ACCOUNT),
	COUNT(DISTINCT OD.DET_ACCOUNT),
	COUNT(DISTINCT AC.DET_ACCOUNT),
	COUNT(DISTINCT ODSB.DET_ACCOUNT),
	CASE
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN 0
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) != 0 THEN (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) != 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) > COUNT(DISTINCT OD.DET_ACCOUNT) THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		ELSE (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
	END,
	SUM(N.NET),
	'Royal Canin, Eukanuba, Hill''s S/P, Brit, Applaws (Cat), Taste of the Wild, N&D, Fisherman''s Daughter, Monge'
FROM
	SL_ACCOUNTS A
	INNER JOIN SL_ACCOUNTS2 A2 ON A.CUCODE = A2.CUCODE2
	LEFT JOIN #ACADISTRIB AD ON A.CUCODE = AD.DET_ACCOUNT
	LEFT JOIN #ORIDISTRIB OD ON A.CUCODE = OD.DET_ACCOUNT
	LEFT JOIN #ACANACHEAP AC ON A.CUCODE = AC.DET_ACCOUNT
	LEFT JOIN #ORIDOGSB ODSB ON A.CUCODE = ODSB.DET_ACCOUNT
	LEFT JOIN #NETSALES N ON A.CUCODE = N.DET_ACCOUNT
WHERE
	CU_DO_NOT_USE = 0 AND
	A2.CU_USRCHAR16 = 'Yes'
UNION ALL
--ROW 5 - ECOM
SELECT
	'5' AS [Order],
	'E-commerce',
	'E-Comm',
	COUNT(DISTINCT CUCODE),
	COUNT(DISTINCT AD.DET_ACCOUNT),
	COUNT(DISTINCT OD.DET_ACCOUNT),
	COUNT(DISTINCT AC.DET_ACCOUNT),
	COUNT(DISTINCT ODSB.DET_ACCOUNT),
	CASE
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN 0
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) != 0 THEN (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) != 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) > COUNT(DISTINCT OD.DET_ACCOUNT) THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		ELSE (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
	END,
	SUM(N.NET),
	'Royal Canin, Eukanuba, Hill''s S/P, Brit, Applaws (Cat), Taste of the Wild, N&D, Fisherman''s Daughter, Monge'
FROM
	SL_ACCOUNTS A
	INNER JOIN SL_ACCOUNTS2 A2 ON A.CUCODE = A2.CUCODE2
	LEFT JOIN #ACADISTRIB AD ON A.CUCODE = AD.DET_ACCOUNT
	LEFT JOIN #ORIDISTRIB OD ON A.CUCODE = OD.DET_ACCOUNT
	LEFT JOIN #ACANACHEAP AC ON A.CUCODE = AC.DET_ACCOUNT
	LEFT JOIN #ORIDOGSB ODSB ON A.CUCODE = ODSB.DET_ACCOUNT
	LEFT JOIN #NETSALES N ON A.CUCODE = N.DET_ACCOUNT
WHERE
	CU_DO_NOT_USE = 0 AND
	CUSORT = '30 PET ECOM'
UNION ALL
--ROW 6 - HOME&GARDEN (ALL 0)
SELECT
	'6' AS [Order],
	'Home&Garden',
	'Home&Garden' AS [Type],
	0 AS [Total Relevant Numeric Distribution Points (# shops in market)],
	0 AS [ACANA Numeric Distribution (# shops ACANA)],
	0 AS [ORIJEN Numeric Distribution (# shops ORIJEN)],
	0 AS [# Shops New ACANA Cat in],
	0 AS [# Shops ORIJEN Small Breed in],
	0 AS [Rate of Sale (avg sell-out per store (local currency))],
	0 AS [Total Turnover per account (local currency)],
	'Royal Canin, Eukanuba, Hill''s S/P, Brit, Applaws (Cat), Taste of the Wild, N&D, Fisherman''s Daughter, Monge' AS [Competitive Benchmark brand's Distribution (which brands we should be targeting in same channel)]
UNION ALL
--ROW 7 - VET&CLINICS
SELECT
	'7' AS [Order],
	'Vet&Clinics',
	'Vet&Clinics',
	COUNT(DISTINCT CUCODE),
	COUNT(DISTINCT AD.DET_ACCOUNT),
	COUNT(DISTINCT OD.DET_ACCOUNT),
	COUNT(DISTINCT AC.DET_ACCOUNT),
	COUNT(DISTINCT ODSB.DET_ACCOUNT),
	CASE
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN 0
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) = 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) != 0 THEN (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) != 0 AND
		COUNT(DISTINCT OD.DET_ACCOUNT) = 0 THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		WHEN COUNT(DISTINCT AD.DET_ACCOUNT) > COUNT(DISTINCT OD.DET_ACCOUNT) THEN (SUM(N.NET) / COUNT(DISTINCT AD.DET_ACCOUNT))
		ELSE (SUM(N.NET) / COUNT(DISTINCT OD.DET_ACCOUNT))
	END,
	SUM(N.NET),
	'Royal Canin, Hill''s P/D, Brit'
FROM
	SL_ACCOUNTS A
	INNER JOIN SL_ACCOUNTS2 A2 ON A.CUCODE = A2.CUCODE2
	LEFT JOIN #ACADISTRIB AD ON A.CUCODE = AD.DET_ACCOUNT
	LEFT JOIN #ORIDISTRIB OD ON A.CUCODE = OD.DET_ACCOUNT
	LEFT JOIN #ACANACHEAP AC ON A.CUCODE = AC.DET_ACCOUNT
	LEFT JOIN #ORIDOGSB ODSB ON A.CUCODE = ODSB.DET_ACCOUNT
	LEFT JOIN #NETSALES N ON A.CUCODE = N.DET_ACCOUNT
WHERE
	CU_DO_NOT_USE = 0 AND
	CUSORT = '30 VET'
DROP TABLE #ACADISTRIB
DROP TABLE #ORIDISTRIB
DROP TABLE #ACANACHEAP
DROP TABLE #ORIDOGSB
DROP TABLE #NETSALES