use vjscl;
declare @stktype NVARCHAR(50);
set @stktype = '30 MORANDO SPA';

WITH DATA AS (
SELECT YEAR(GETDATE()) AS Y, YEAR(GETDATE())-1 AS Y_1, YEAR(GETDATE())-2 AS Y_2, STK_SORT_KEY, STK_SORT_KEY1, STKCODE, STKNAME, STK_SORT_KEY3, STK_USRFLAG1 AS DoNotLoad, 
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C1 / S.STK_EC_SUP_UNIT END AS 'JAN Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C2 / S.STK_EC_SUP_UNIT END AS 'FEB Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C3 / S.STK_EC_SUP_UNIT END AS 'MAR Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C4 / S.STK_EC_SUP_UNIT END AS 'APR Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C5 / S.STK_EC_SUP_UNIT END AS 'MAY Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C6 / S.STK_EC_SUP_UNIT END AS 'JUN Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C7 / S.STK_EC_SUP_UNIT END AS 'JUL Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C8 / S.STK_EC_SUP_UNIT END AS 'AUG Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C9 / S.STK_EC_SUP_UNIT END AS 'SEP Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C10 / S.STK_EC_SUP_UNIT END AS 'OCT Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C11 / S.STK_EC_SUP_UNIT END AS 'NOV Y-1',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE CY.STK_MOVEOUT_C12 / S.STK_EC_SUP_UNIT END AS 'DEC Y-1',

CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N1 / S.STK_EC_SUP_UNIT END AS 'JAN Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N2 / S.STK_EC_SUP_UNIT END AS 'FEB Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N3 / S.STK_EC_SUP_UNIT END AS 'MAR Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N4 / S.STK_EC_SUP_UNIT END AS 'APR Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N5 / S.STK_EC_SUP_UNIT END AS 'MAY Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N6 / S.STK_EC_SUP_UNIT END AS 'JUN Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N7 / S.STK_EC_SUP_UNIT END AS 'JUL Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N8 / S.STK_EC_SUP_UNIT END AS 'AUG Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N9 / S.STK_EC_SUP_UNIT END AS 'SEP Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N10 / S.STK_EC_SUP_UNIT END AS 'OCT Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N11 / S.STK_EC_SUP_UNIT END AS 'NOV Y',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE NY.STK_MOVEOUT_N12 / S.STK_EC_SUP_UNIT END AS 'DEC Y',

CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L1 / S.STK_EC_SUP_UNIT END AS 'JAN Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L2 / S.STK_EC_SUP_UNIT END AS 'FEB Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L3 / S.STK_EC_SUP_UNIT END AS 'MAR Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L4 / S.STK_EC_SUP_UNIT END AS 'APR Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L5 / S.STK_EC_SUP_UNIT END AS 'MAY Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L6 / S.STK_EC_SUP_UNIT END AS 'JUN Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L7 / S.STK_EC_SUP_UNIT END AS 'JUL Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L8 / S.STK_EC_SUP_UNIT END AS 'AUG Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L9 / S.STK_EC_SUP_UNIT END AS 'SEP Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L10 / S.STK_EC_SUP_UNIT END AS 'OCT Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L11 / S.STK_EC_SUP_UNIT END AS 'NOV Y-2',
CASE WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 ELSE LY.STK_MOVEOUT_L12 / S.STK_EC_SUP_UNIT END AS 'DEC Y-2', 
STK_USRCHAR12, Total_NY, Total_CY, Total_LY, STK_USRNUM1, 
STK_USRFLAG8 AS SellOnlyCases, STK_EC_SUP_UNIT, STK_PHYSICAL, STK_ORDER_IN, STK_USRFLAG3 AS Delisted
FROM STK_STOCK3 S3
INNER JOIN STK_STOCK S ON S3.STKCODE3=S.STKCODE 
INNER JOIN VJSCL_STK_MOVEMENTS_NY NY ON S.STKCODE=NY.SM_STOCK_CODE 
INNER JOIN (SELECT LOC_STOCK_CODE, SUM(LOC_PHYSICAL) AS TOT_PHYSICAL FROM STK_LOCATION GROUP BY LOC_STOCK_CODE) L ON S.STKCODE=L.LOC_STOCK_CODE 
INNER JOIN VJSCL_STK_MOVEMENTS_CY CY ON CY.SM_STOCK_CODE=NY.SM_STOCK_CODE 
INNER JOIN VJSCL_STK_MOVEMENTS_LY LY ON LY.SM_STOCK_CODE=CY.SM_STOCK_CODE
WHERE STK_USRFLAG2 = 1
AND STK_SORT_KEY3=@stktype
AND L.TOT_PHYSICAL > 0
)

SELECT StkCode, Y as [Year], [Jan Y],[Feb Y],[Mar Y],[Apr Y],[May Y],[Jun Y],[Jul Y],[Aug Y],[Sep Y],[Oct Y],[Nov Y],[Dec Y],[Jan Y]+[Feb Y]+[Mar Y]+[Apr Y]+[May Y]+[Jun Y]+[Jul Y]+[Aug Y]+[Sep Y]+[Oct Y]+[Nov Y]+[Dec Y] as Total
FROM Data
UNION ALL 
SELECT StkCode, Y_1 as [Year], [Jan Y-1],[Feb Y-1],[Mar Y-1],[Apr Y-1],[May Y-1],[Jun Y-1],[Jul Y-1],[Aug Y-1],[Sep Y-1],[Oct Y-1],[Nov Y-1],[Dec Y-1],[Jan Y-1]+[Feb Y-1]+[Mar Y-1]+[Apr Y-1]+[May Y-1]+[Jun Y-1]+[Jul Y-1]+[Aug Y-1]+[Sep Y-1]+[Oct Y-1]+[Nov Y-1]+[Dec Y-1] as Total
FROM Data
UNION ALL 
SELECT StkCode, Y_2 as [Year], [Jan Y-2],[Feb Y-2],[Mar Y-2],[Apr Y-2],[May Y-2],[Jun Y-2],[Jul Y-2],[Aug Y-2],[Sep Y-2],[Oct Y-2],[Nov Y-2],[Dec Y-2],[Jan Y-2]+[Feb Y-2]+[Mar Y-2]+[Apr Y-2]+[May Y-2]+[Jun Y-2]+[Jul Y-2]+[Aug Y-2]+[Sep Y-2]+[Oct Y-2]+[Nov Y-2]+[Dec Y-2] as Total
FROM Data