DECLARE @stktype NVARCHAR(50);

SET
    @stktype = '30 MPM PRODUCTS LTD.';

SELECT
    STKCODE,
    LOC_CODE,
    CASE
        WHEN S.STK_EC_SUP_UNIT = 0 THEN 0
        ELSE LOC_PHYSICAL / S.STK_EC_SUP_UNIT
    END AS LOC_PHYSICAL,
    CAST(LOC_USERDATE1 AS DATE) AS ExpiryDate
FROM
    STK_STOCK3 S3
    INNER JOIN STK_STOCK S ON S3.STKCODE3 = S.STKCODE
    INNER JOIN STK_LOCATION L ON S.STKCODE = L.LOC_STOCK_CODE
    INNER JOIN STK_LOCATION2 L2 ON L.LOC_CODE = L2.LOC_CODE2 AND
    L.LOC_STOCK_CODE = L2.LOC_STOCKCODE2
WHERE
    STK_SORT_KEY3 = @stktype AND
    STK_USRFLAG2 = 1 AND
    LOC_PHYSICAL > 0
ORDER BY
    STK_SORT_KEY,
    STK_SORT_KEY1,
    STKCODE,
    LOC_CODE