SELECT STK_SORT_KEY3 AS SUPPLIER, 
STK_SORT_KEY AS BRAND, 
STK_SORT_KEY1 AS SubCategory,
S2.STK_SUPSTKCDE1 AS SupplierCode, MIN(STKNAME) AS STKNAME, S2.STK_SUPSTKCDE1+' | '+MIN(STKNAME) AS STK_CN,
 STK_USRNUM1 AS POMinQty,
 S3.STK_USRNUM4 AS MIN_STK_QTY, 
 S3.STK_USRNUM5 AS MAX_STK_QTY,
 S3.STK_USRNUM6 AS 'UNITS_PER_PALLET',
  S3.STK_USRNUM7 AS 'UNITS_PER_LAYER',
 CAST(Z.[3M_AVG] AS INT) AS [3M_AVG], 
 CAST(Z2.[12M_AVG] AS INT) AS [12M_AVG],
 LOC.STK_PHYSICAL+SUM(STK_ORDER_IN) AS CURRENT_STOCK_QTY,
 CASE WHEN Z.[3M_AVG]=0 THEN 0 ELSE CAST((LOC.STK_PHYSICAL+SUM(STK_ORDER_IN))/Z.[3M_AVG] AS DECIMAL (18,2)) END AS CURRENT_STOCK_COVERAGE,
 CASE WHEN 
	(CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1 END) < 0 THEN 0 ELSE 
		CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1 END END AS AUTO_ORDER_QTY,
 CASE WHEN 
	(CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1 END) < 0 THEN 0 ELSE 
		CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE CASE WHEN Z.[3M_AVG]=0 THEN 0 ELSE CAST((LOC.STK_PHYSICAL+SUM(STK_ORDER_IN)+(ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1))/Z.[3M_AVG] AS DECIMAL (18,2)) END END END AS AUTO_ORDER_COVERAGE,
 CASE WHEN 
	(CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1 END) < 0 THEN 0 ELSE 
		CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE CASE WHEN STK_USRNUM6=0 THEN 0 ELSE CAST(ROUND((ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1)/S3.STK_USRNUM6,2) AS DECIMAL(18,2)) END END END AS AUTO_ORDER_PALLETS,
CASE WHEN 
	(CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1 END) < 0 THEN 0 ELSE 
		CASE WHEN STK_USRNUM1=0 OR STK_USRNUM1 IS NULL THEN 0 ELSE CASE WHEN STK_USRNUM7=0 THEN 0 ELSE CAST(ROUND((ROUND(FLOOR((S3.STK_USRNUM5*Z.[3M_AVG])-LOC.STK_PHYSICAL-SUM(STK_ORDER_IN))/STK_USRNUM1,0)*STK_USRNUM1)/S3.STK_USRNUM7,2) AS DECIMAL(18,2)) END END END AS AUTO_ORDER_LAYERS
 FROM STK_STOCK S
 INNER JOIN STK_STOCK_2 s2 ON S.STKCODE=S2.STKCODE2
 INNER JOIN STK_STOCK3 S3 ON S3.STKCODE3=S.STKCODE
 LEFT JOIN (
	select STK_SUPSTKCDE1, sum(case when det_type = 'CRN' then det_quantity*-1 else DET_QUANTITY end)/3 as [3M_AVG] 
	from SL_PL_NL_DETAIL
	INNER JOIN STK_STOCK3 S3 ON S3.STKCODE3=DET_STOCK_CODE
	INNER JOIN STK_STOCK_2 S2 ON DET_STOCK_CODE=S2.STKCODE2
	where det_date between cast(getdate()-91 as date) and cast(getdate()-1 as date) and det_type in ('INV','CRN') AND DET_LEDGER = 'SL' AND DET_STKSORTKEY3 = '30 HILLS PET NUTRI.' AND STK_USRFLAG3 = 0 AND STK_USRFLAG2 = 1
	group by STK_SUPSTKCDE1) Z
 ON Z.STK_SUPSTKCDE1=S2.STK_SUPSTKCDE1
 LEFT JOIN (
	select STK_SUPSTKCDE1, sum(case when det_type = 'CRN' then det_quantity*-1 else DET_QUANTITY end)/12 as [12M_AVG] 
	from SL_PL_NL_DETAIL 
	INNER JOIN STK_STOCK3 S3 ON S3.STKCODE3=DET_STOCK_CODE
	INNER JOIN STK_STOCK_2 S2 ON DET_STOCK_CODE=S2.STKCODE2
	where det_date between cast(getdate()-366 as date) and cast(getdate()-1 as date) and det_type in ('INV','CRN') AND DET_LEDGER = 'SL' AND DET_STKSORTKEY3 = '30 HILLS PET NUTRI.' AND STK_USRFLAG3 = 0 AND STK_USRFLAG2 = 1
	group by STK_SUPSTKCDE1) Z2
 ON Z2.STK_SUPSTKCDE1=S2.STK_SUPSTKCDE1
 LEFT JOIN (
	SELECT STK_SUPSTKCDE1, SUM(LOC_PHYSICAL) AS STK_PHYSICAL
	FROM STK_LOCATION SL
	INNER JOIN STK_STOCK_2 S2 ON S2.STKCODE2=SL.LOC_STOCK_CODE
	WHERE LOC_USERSORT1 NOT IN ('WHZ','WHY','WSC')
	GROUP BY STK_SUPSTKCDE1) LOC
ON S2.STK_SUPSTKCDE1=LOC.STK_SUPSTKCDE1
WHERE STK_SORT_KEY3 = '30 HILLS PET NUTRI.' AND STK_USRFLAG2 = 1
GROUP BY STK_SORT_KEY3, STK_SORT_KEY, STK_SORT_KEY1,S2.STK_SUPSTKCDE1, STK_USRNUM1, S3.STK_USRNUM4,  S3.STK_USRNUM5,
 S3.STK_USRNUM6,  S3.STK_USRNUM7, Z.[3M_AVG] ,Z2.[12M_AVG] , LOC.STK_PHYSICAL
ORDER BY STK_SORT_KEY, STK_SORT_KEY1, s2.STK_SUPSTKCDE1