 SELECT S2.STK_SUPSTKCDE1 AS SUPPLIERCODE, LOC_CODE, SUM(LOC_PHYSICAL) as LOC_PHYSICAL, CAST(LOC_USERDATE1 as Date) AS ExpiryDate
 FROM STK_STOCK3 S3
 INNER JOIN STK_STOCK S ON S3.STKCODE3=S.STKCODE 
 INNER JOIN STK_STOCK_2 S2 ON S.STKCODE=S2.STKCODE2
 INNER JOIN STK_LOCATION L ON S.STKCODE=L.LOC_STOCK_CODE 
 INNER JOIN STK_LOCATION2 L2 ON L.LOC_CODE=L2.LOC_CODE2 AND L.LOC_STOCK_CODE=L2.LOC_STOCKCODE2
 WHERE STK_SORT_KEY3='30 HILLS PET NUTRI.'
 AND STK_USRFLAG2 = 1
 AND LOC_PHYSICAL > 0 
 GROUP BY S2.STK_SUPSTKCDE1,LOC_CODE, LOC_USERDATE1
