SELECT STK_SORT_KEY3 AS SUPPLIER, 
STK_SORT_KEY AS BRAND, 
STK_SORT_KEY1 AS CATEGORY,
STK_SORT_KEY2 AS [TYPE],
S2.STK_SUPSTKCDE1 AS SupplierCode,
STKCODE, 
STKNAME, 
STKCODE+' | '+STKNAME AS STK_CN,
 CASE 
    WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 
    ELSE STK_USRNUM1 / S.STK_EC_SUP_UNIT 
 END AS POMinQty,
 S3.STK_USRNUM4 AS MIN_STK_QTY, 
 S3.STK_USRNUM5 AS MAX_STK_QTY,
 S3.STK_USRNUM6 AS 'UNITS_PER_PALLET',
 s.stk_ec_sup_unit AS 'UNITS_PER_CASE',
 CAST(Z.[3M_AVG] AS INT) AS [3M_AVG], 
 CAST(Z2.[12M_AVG] AS INT) AS [12M_AVG],
  CASE 
    WHEN S.STK_EC_SUP_UNIT = 0 THEN 0 
    ELSE (LOC.STK_PHYSICAL + STK_ORDER_IN) / S.STK_EC_SUP_UNIT 
  END AS CURRENT_STOCK_QTY,
 CASE WHEN S.STK_EC_SUP_UNIT = 0 THEN 0 ELSE LOC.STK_PHYSICAL/S.STK_EC_SUP_UNIT END AS LOC_PHYSICAL,
 CASE WHEN S.STK_EC_SUP_UNIT = 0 THEN 0 ELSE STK_ORDER_IN/S.STK_EC_SUP_UNIT END AS STK_ORDER_IN,
   CASE 
    WHEN Z.[3M_AVG] = 0 THEN 0 
    ELSE CAST(
      CASE 
        WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0 
        ELSE (LOC.STK_PHYSICAL + STK_ORDER_IN) / S.STK_EC_SUP_UNIT 
      END / Z.[3M_AVG] AS DECIMAL(18,2)
    ) 
  END AS CURRENT_STOCK_COVERAGE,
  CASE 
    WHEN STK_USRNUM1 = 0 OR STK_USRNUM1 IS NULL OR S.STK_EC_SUP_UNIT = 0 THEN 0 
    ELSE 
      CASE 
        WHEN FLOOR(((S3.STK_USRNUM5 * Z.[3M_AVG]*S.STK_EC_SUP_UNIT) - LOC.STK_PHYSICAL - STK_ORDER_IN) 
                    / S.STK_EC_SUP_UNIT) / (STK_USRNUM1 / S.STK_EC_SUP_UNIT) < 0 
        THEN 0 
        ELSE 
          ROUND(
            FLOOR(
              ((S3.STK_USRNUM5 * Z.[3M_AVG] * S.STK_EC_SUP_UNIT) - LOC.STK_PHYSICAL - STK_ORDER_IN) 
              / S.STK_EC_SUP_UNIT
            ) / (STK_USRNUM1 / S.STK_EC_SUP_UNIT), 0
          ) * STK_USRNUM1
      END 
  END AS AUTO_ORDER_QTY,
CASE 
    WHEN STK_USRNUM1 = 0 OR STK_USRNUM1 IS NULL OR S.STK_EC_SUP_UNIT = 0 THEN 0 
    ELSE 
      CASE 
        WHEN FLOOR(
          ((S3.STK_USRNUM5 * Z.[3M_AVG] * S.STK_EC_SUP_UNIT) - LOC.STK_PHYSICAL - STK_ORDER_IN)
          / S.STK_EC_SUP_UNIT
        ) / (STK_USRNUM1 / S.STK_EC_SUP_UNIT) < 0 THEN 0 
        ELSE 
          CASE 
            WHEN Z.[3M_AVG] = 0 THEN 0 
            ELSE CAST(
              (
                LOC.STK_PHYSICAL + STK_ORDER_IN + 
                ROUND(
                  FLOOR(
                    ((S3.STK_USRNUM5 * Z.[3M_AVG] * S.STK_EC_SUP_UNIT) - LOC.STK_PHYSICAL - STK_ORDER_IN)
                    / S.STK_EC_SUP_UNIT
                  ) / (STK_USRNUM1 / S.STK_EC_SUP_UNIT), 0
                ) * STK_USRNUM1
              ) / (Z.[3M_AVG]*S.STK_EC_SUP_UNIT) AS DECIMAL(18, 2)
            ) 
          END 
      END 
  END AS AUTO_ORDER_COVERAGE,
CASE 
    WHEN STK_USRNUM1 = 0 OR STK_USRNUM1 IS NULL OR S.STK_EC_SUP_UNIT = 0 THEN 0 
    ELSE 
      CASE 
        WHEN FLOOR(
              ((S3.STK_USRNUM5 * Z.[3M_AVG] * S.STK_EC_SUP_UNIT) - LOC.STK_PHYSICAL - STK_ORDER_IN)
              / S.STK_EC_SUP_UNIT
            ) / (STK_USRNUM1 / S.STK_EC_SUP_UNIT) < 0 THEN 0 
        ELSE 
          CASE 
            WHEN STK_USRNUM6 = 0 OR STK_USRNUM6 IS NULL THEN 0 
            ELSE CAST(
              ROUND(
                (
                  ROUND(
                    FLOOR(
                      ((S3.STK_USRNUM5 * Z.[3M_AVG] * S.STK_EC_SUP_UNIT) - LOC.STK_PHYSICAL - STK_ORDER_IN)
                      / S.STK_EC_SUP_UNIT
                    ) / (STK_USRNUM1 / S.STK_EC_SUP_UNIT), 0
                  ) * STK_USRNUM1
                ) / STK_USRNUM6, 2
              ) AS DECIMAL(18, 2)
            )
          END 
      END 
  END AS AUTO_ORDER_PALLETS

 FROM STK_STOCK S
 INNER JOIN STK_STOCK_2 s2 ON S.STKCODE=S2.STKCODE2
 INNER JOIN STK_STOCK3 S3 ON S3.STKCODE3=S.STKCODE
 LEFT JOIN (
  SELECT 
    DET_STOCK_CODE, 
    SUM(
      CASE 
        WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0
        ELSE 
          (CASE WHEN DET_TYPE = 'CRN' THEN DET_QUANTITY * -1 ELSE DET_QUANTITY END) / S.STK_EC_SUP_UNIT
      END
    ) / 3 AS [3M_AVG]
  FROM SL_PL_NL_DETAIL
	INNER JOIN STK_STOCK3 S3 ON S3.STKCODE3=DET_STOCK_CODE
	INNER JOIN STK_STOCK S ON DET_STOCK_CODE = S.STKCODE
	where det_date between cast(getdate()-91 as date) and cast(getdate()-1 as date) and det_type in ('INV','CRN') AND DET_LEDGER = 'SL' AND DET_STKSORTKEY3 = '30 DR SCHAR' AND DET_STKSORTKEY1 = '30 SCH FROZEN' AND STK_USRFLAG3 = 0 AND STK_USRFLAG2 = 1
	group by DET_STOCK_CODE) Z
 ON Z.DET_STOCK_CODE=S.STKCODE
 LEFT JOIN (
  SELECT 
    DET_STOCK_CODE, 
    SUM(
      CASE 
        WHEN S.STK_EC_SUP_UNIT = 0 OR S.STK_EC_SUP_UNIT IS NULL THEN 0
        ELSE 
          (CASE WHEN DET_TYPE = 'CRN' THEN DET_QUANTITY * -1 ELSE DET_QUANTITY END) / S.STK_EC_SUP_UNIT
      END
    ) / 12 AS [12M_AVG]
  FROM SL_PL_NL_DETAIL
	INNER JOIN STK_STOCK3 S3 ON S3.STKCODE3=DET_STOCK_CODE
	INNER JOIN STK_STOCK S ON DET_STOCK_CODE = S.STKCODE
	where det_date between cast(getdate()-366 as date) and cast(getdate()-1 as date) and det_type in ('INV','CRN') AND DET_LEDGER = 'SL' AND DET_STKSORTKEY3 = '30 DR SCHAR' AND DET_STKSORTKEY1 = '30 SCH FROZEN' AND STK_USRFLAG3 = 0 AND STK_USRFLAG2 = 1
	group by DET_STOCK_CODE) Z2
 ON Z2.DET_STOCK_CODE=S.STKCODE
 LEFT JOIN (
	SELECT LOC_STOCK_CODE, SUM(LOC_PHYSICAL) AS STK_PHYSICAL
	FROM STK_LOCATION L
	INNER JOIN STK_LOCATION2 L2 ON L.LOC_STOCK_CODE=L2.LOC_STOCKCODE2 AND L.LOC_CODE=L2.LOC_CODE2
	WHERE LOC_USERSORT1 NOT IN ('WHZ','WHY','WSC') AND LOC_USERDATE1 >= GETDATE()
	GROUP BY LOC_STOCK_CODE) LOC
ON S.STKCODE=LOC.LOC_STOCK_CODE
WHERE STK_SORT_KEY3 = '30 DR SCHAR' AND STK_SORT_KEY1 = '30 SCH FROZEN' AND STK_USRFLAG2 = 1