USE vjscl;

SELECT
	T.BRAND,
	T.SubCategory,
	S.[CategManager],
	S.[Full Name],
	SUM(T.[Target1]) AS 'Target1',
	SUM(T.[Target2]) AS 'Target2' INTO #TGT
FROM
	Spot.[dbo].[VJSCL_Exec_Targets] T
	INNER JOIN (
		SELECT DISTINCT
			S.STK_SORT_KEY AS 'Brand',
			CASE S.STK_SORT_KEY
				WHEN '30 NIVEA' THEN S.STK_SORT_KEY1
				WHEN '30 HILLS PET' THEN CASE
					WHEN LEFT(S.STK_SORT_KEY1, 9) IN ('30 HIL PD', '30 HIL VE') THEN '30 HIL PD'
					WHEN LEFT(S.STK_SORT_KEY1, 9) = '30 HIL SP' THEN '30 HIL SP'
					ELSE NULL
				END
			END AS 'SubCat',
			S3.STK_USRCHAR18 AS [CategManager],
			E.[Full Name]
		FROM
			STK_STOCK S
			INNER JOIN STK_STOCK3 S3 ON S.STKCODE = S3.STKCODE3
			INNER JOIN [Spot].dbo.[CategoryManagers] E ON S3.STK_USRCHAR18 = E.[Category Number]
		WHERE
			S3.STK_USRFLAG3 = 0 AND
			LEFT(S.STK_SORT_KEY1, 9) != '30 HIL PR'
	) S ON S.Brand = T.Brand AND
	CASE
		WHEN S.SubCat IS NULL THEN 'A'
		ELSE S.SubCat
	END = CASE
		WHEN T.SubCategory IS NULL THEN 'A'
		ELSE T.SubCategory
	END
WHERE
	T.Year = YEAR(GETDATE())
GROUP BY
	T.BRAND,
	T.SubCategory,
	S.[CategManager],
	S.[Full Name];

select * from #TGT;

SELECT
	A.CUUSER2 AS CUST_CATEG,
	S.STK_SORT_KEY AS 'Brand',
	CASE S.STK_SORT_KEY
		WHEN '30 NIVEA' THEN S.STK_SORT_KEY1
		WHEN '30 HILLS PET' THEN CASE
			WHEN LEFT(S.STK_SORT_KEY1, 9) IN ('30 HIL PD', '30 HIL VE') THEN '30 HIL PD'
			WHEN LEFT(S.STK_SORT_KEY1, 9) = '30 HIL SP' THEN '30 HIL SP'
		END
	END AS 'SubCat',
	ROUND(
		SUM(
			CASE
				WHEN YEAR(DET_DATE) = YEAR(GETDATE()) -2 THEN (
					CASE
						WHEN DET_TYPE = 'INV' THEN DET_NETT
						ELSE DET_NETT * -1
					END
				)
				ELSE 0
			END
		),
		2
	) AS NET_LY2,
	ROUND(
		SUM(
			CASE
				WHEN YEAR(DET_DATE) = YEAR(GETDATE()) -1 THEN (
					CASE
						WHEN DET_TYPE = 'INV' THEN DET_NETT
						ELSE DET_NETT * -1
					END
				)
				ELSE 0
			END
		),
		2
	) AS NET_LY,
	ROUND(
		SUM(
			CASE
				WHEN YEAR(DET_DATE) = YEAR(GETDATE()) -1 AND
				DET_DATE <= CAST(DATEADD(YEAR, -1, GETDATE()) AS DATE) THEN (
					CASE
						WHEN DET_TYPE = 'INV' THEN DET_NETT
						ELSE DET_NETT * -1
					END
				)
				ELSE 0
			END
		),
		2
	) AS NET_LYTD,
	ROUND(
		SUM(
			CASE
				WHEN YEAR(DET_DATE) = YEAR(GETDATE()) THEN (
					CASE
						WHEN DET_TYPE = 'INV' THEN DET_NETT
						ELSE DET_NETT * -1
					END
				)
				ELSE 0
			END
		),
		2
	) AS NET_CYTD INTO #SLS
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN SL_TRANSACTIONS T ON D.DET_HEADER_KEY = T.ST_HEADER_KEY
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
	INNER JOIN SL_ACCOUNTS A ON D.DET_ACCOUNT = A.CUCODE
WHERE
	D.DET_ORIGIN = 'SO' AND
	D.DET_TYPE IN ('INV', 'CRN') AND
	YEAR(D.DET_DATE) >= YEAR(GETDATE()) -2 AND
	LEFT(S.STK_SORT_KEY1, 9) != '30 HIL PR' AND
	T.ST_USER1 != '30 OFFICE' AND
	A.CUUSER2 != '30 OFFICE'
GROUP BY
	A.CUUSER2,
	S.STK_SORT_KEY,
	CASE S.STK_SORT_KEY
		WHEN '30 NIVEA' THEN S.STK_SORT_KEY1
		WHEN '30 HILLS PET' THEN CASE
			WHEN LEFT(S.STK_SORT_KEY1, 9) IN ('30 HIL PD', '30 HIL VE') THEN '30 HIL PD'
			WHEN LEFT(S.STK_SORT_KEY1, 9) = '30 HIL SP' THEN '30 HIL SP'
			ELSE NULL
		END
	END;

select * from #SLS;

SELECT
	S.STK_SORT_KEY AS 'Brand',
	CASE S.STK_SORT_KEY
		WHEN '30 NIVEA' THEN S.STK_SORT_KEY1
		WHEN '30 HILLS PET' THEN CASE
			WHEN LEFT(S.STK_SORT_KEY1, 9) IN ('30 HIL PD', '30 HIL VE') THEN '30 HIL PD'
			WHEN LEFT(S.STK_SORT_KEY1, 9) = '30 HIL SP' THEN '30 HIL SP'
		END
	END AS 'SubCat',
	ROUND(
		SUM(
			CASE
				WHEN DET_TYPE = 'INV' THEN DET_NETT
				ELSE DET_NETT * -1
			END
		),
		2
	) AS BRAND_NET INTO #BRAND
FROM
	SL_PL_NL_DETAIL D
	INNER JOIN SL_TRANSACTIONS T ON D.DET_HEADER_KEY = T.ST_HEADER_KEY
	INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE = S.STKCODE
	INNER JOIN SL_ACCOUNTS A ON D.DET_ACCOUNT = A.CUCODE
WHERE
	D.DET_ORIGIN = 'SO' AND
	D.DET_TYPE IN ('INV', 'CRN') AND
	YEAR(D.DET_DATE) = YEAR(GETDATE()) -1 AND
	LEFT(S.STK_SORT_KEY1, 9) != '30 HIL PR' AND
	T.ST_USER1 != '30 OFFICE' AND
	A.CUUSER2 != '30 OFFICE'
GROUP BY
	S.STK_SORT_KEY,
	CASE S.STK_SORT_KEY
		WHEN '30 NIVEA' THEN S.STK_SORT_KEY1
		WHEN '30 HILLS PET' THEN CASE
			WHEN LEFT(S.STK_SORT_KEY1, 9) IN ('30 HIL PD', '30 HIL VE') THEN '30 HIL PD'
			WHEN LEFT(S.STK_SORT_KEY1, 9) = '30 HIL SP' THEN '30 HIL SP'
			ELSE NULL
		END
	END;

select * from #BRAND;

SELECT
	T.[Full Name],
	ROUND(
		(
			CAST(DATEPART(WEEK, GETDATE()) AS DECIMAL(18, 2)) / 52
		) * 100,
		0
	) AS GOAL_PERC,
	S.CUST_CATEG,
	T.Brand,
	T.SubCategory,
	NET_LY2,
	NET_LY,
	(NET_LY / BRAND_NET) * 100 AS TEST,
	ROUND((NET_LY / BRAND_NET) * T.Target1, 2) AS [TARGET1],
	S.NET_CYTD,
	S.NET_LYTD,
	S.NET_CYTD - ROUND((NET_LY / BRAND_NET) * T.Target1, 2) AS [TARGET1_DIFF],
	CASE
		WHEN ROUND((NET_LY / BRAND_NET) * T.Target1, 2) = 0 THEN 0
		ELSE ROUND(
			S.NET_CYTD / ROUND((NET_LY / BRAND_NET) * T.Target1, 2) * 100,
			0
		)
	END AS PERC_TARGET1,
	ROUND((NET_LY / BRAND_NET) * T.Target2, 2) AS [TARGET2],
	S.NET_CYTD - ROUND((NET_LY / BRAND_NET) * T.Target2, 2) AS [TARGET2_DIFF],
	CASE
		WHEN ROUND((NET_LY / BRAND_NET) * T.Target2, 2) = 0 THEN 0
		ELSE ROUND(
			S.NET_CYTD / ROUND((NET_LY / BRAND_NET) * T.Target2, 2) * 100,
			0
		)
	END AS PERC_TARGET2
FROM
	#TGT T
	INNER JOIN #SLS S ON T.Brand = S.Brand AND
	CASE
		WHEN S.SubCat IS NULL THEN 'A'
		ELSE S.SubCat
	END = CASE
		WHEN T.SubCategory IS NULL THEN 'A'
		ELSE T.SubCategory
	END
	INNER JOIN #BRAND B ON T.Brand = B.Brand AND
	CASE
		WHEN B.SubCat IS NULL THEN 'A'
		ELSE B.SubCat
	END = CASE
		WHEN T.SubCategory IS NULL THEN 'A'
		ELSE T.SubCategory
	END
WHERE
	T.[Full Name] IN ('Luke Gauci', 'Naomi Abela')
UNION ALL
SELECT
	T.[Full Name],
	ROUND(
		(
			CAST(DATEPART(WEEK, GETDATE()) AS DECIMAL(18, 2)) / 52
		) * 100,
		0
	) AS GOAL_PERC,
	'TOTAL',
	T.Brand,
	T.SubCategory,
	SUM(NET_LY2) AS TOT_LY2,
	SUM(NET_LY) AS TOT_LY,
	SUM((NET_LY / BRAND_NET) * 100) AS TEST,
	T.Target1,
	SUM(S.NET_CYTD) AS TOT_CYTD,
	SUM(S.NET_LYTD) AS TOT_LYTD,
	SUM(S.NET_CYTD) - T.Target1 AS [TARGET1_DIFF],
	CASE
		WHEN T.Target1 = 0 THEN 0
		ELSE ROUND(SUM(S.NET_CYTD) / T.Target1 * 100, 0)
	END AS PERC_TARGET1,
	T.Target2,
	SUM(S.NET_CYTD) - T.Target2 AS [TARGET2_DIFF],
	CASE
		WHEN T.Target2 = 0 THEN 0
		ELSE ROUND(SUM(S.NET_CYTD) / T.Target2 * 100, 0)
	END AS PERC_TARGET2
FROM
	#TGT T
	INNER JOIN #SLS S ON T.Brand = S.Brand AND
	CASE
		WHEN S.SubCat IS NULL THEN 'A'
		ELSE S.SubCat
	END = CASE
		WHEN T.SubCategory IS NULL THEN 'A'
		ELSE T.SubCategory
	END
	INNER JOIN #BRAND B ON T.Brand = B.Brand AND
	CASE
		WHEN B.SubCat IS NULL THEN 'A'
		ELSE B.SubCat
	END = CASE
		WHEN T.SubCategory IS NULL THEN 'A'
		ELSE T.SubCategory
	END
WHERE
	T.[Full Name] IN ('Luke Gauci', 'Naomi Abela')
GROUP BY
	T.[Full Name],
	T.Brand,
	T.SubCategory,
	T.Target1,
	T.Target2