SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO





ALTER view [dbo].[VJSCL_SM_CY_TMP_CasesUnit]
as

select top 100percent
stkcode as sm_stock_code,
STK_MOVEOUT_C1,STK_MOVEOUT_C2,STK_MOVEOUT_C3,STK_MOVEOUT_C4,STK_MOVEOUT_C5,STK_MOVEOUT_C6,
STK_MOVEOUT_C7,STK_MOVEOUT_C8,STK_MOVEOUT_C9,STK_MOVEOUT_C10,STK_MOVEOUT_C11,STK_MOVEOUT_C12
from
(
SELECT     stkcode,
SUM(CASE SM_PERIODNUM WHEN 1 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C1,
SUM(CASE SM_PERIODNUM WHEN 2 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C2,
SUM(CASE SM_PERIODNUM WHEN 3 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C3,
SUM(CASE SM_PERIODNUM WHEN 4 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C4,
SUM(CASE SM_PERIODNUM WHEN 5 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C5,
SUM(CASE SM_PERIODNUM WHEN 6 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C6,
SUM(CASE SM_PERIODNUM WHEN 7 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C7,
SUM(CASE SM_PERIODNUM WHEN 8 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C8,
SUM(CASE SM_PERIODNUM WHEN 9 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C9,
SUM(CASE SM_PERIODNUM WHEN 10 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C10,
SUM(CASE SM_PERIODNUM WHEN 11 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C11,
SUM(CASE SM_PERIODNUM WHEN 12 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN SM_QUANTITY * -1 ELSE SM_QUANTITY END) ELSE 0 END) AS STK_MOVEOUT_C12
FROM stk_stock S    
INNER JOIN STK_STOCK3 S3 on s3.STKCODE3=S.STKCODE
LEFT JOIN STK_MOVEMENTS  on stkcode = SM_STOCK_CODE
AND YEAR(SM_DATE)= YEAR(GETDATE()) -1
AND SM_TYPE='S'
WHERE    --SM_YEAR = 'C' 
STK_USRFLAG8 = 0
GROUP BY stkcode
union all
SELECT     stkcode as sm_stock_code,
SUM(CASE SM_PERIODNUM WHEN 1 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C1,
SUM(CASE SM_PERIODNUM WHEN 2 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C2,
SUM(CASE SM_PERIODNUM WHEN 3 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C3,
SUM(CASE SM_PERIODNUM WHEN 4 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C4,
SUM(CASE SM_PERIODNUM WHEN 5 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C5,
SUM(CASE SM_PERIODNUM WHEN 6 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C6,
SUM(CASE SM_PERIODNUM WHEN 7 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C7,
SUM(CASE SM_PERIODNUM WHEN 8 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C8,
SUM(CASE SM_PERIODNUM WHEN 9 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C9,
SUM(CASE SM_PERIODNUM WHEN 10 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C10,
SUM(CASE SM_PERIODNUM WHEN 11 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C11,
SUM(CASE SM_PERIODNUM WHEN 12 THEN (CASE WHEN (SM_TYPE = 'S' AND SM_STATUS = 'I') THEN (SM_quantity/STK_EC_SUP_UNIT) * -1 ELSE (SM_quantity/STK_EC_SUP_UNIT) END) ELSE 0 END) AS STK_MOVEOUT_C12
FROM stk_stock S     
INNER JOIN STK_STOCK3 S3 on s3.STKCODE3=S.STKCODE
LEFT JOIN STK_MOVEMENTS on stkcode = SM_STOCK_CODE
AND YEAR(SM_DATE)= YEAR(GETDATE()) -1
AND SM_TYPE='S'
WHERE    --SM_YEAR = 'C' 
STK_USRFLAG8 = 1
and STK_EC_SUP_UNIT <> 0
GROUP BY stkcode
)z

order by 1




GO
