SELECT
    "STK_STOCK"."STK_SORT_KEY",
    "STK_STOCK"."STK_SORT_KEY1",
    "STK_STOCK"."STKCODE",
    "STK_STOCK"."STKNAME",
    "STK_STOCK"."STK_SORT_KEY3",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C1",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C2",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C3",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C4",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C5",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C6",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C7",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C8",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C9",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C10",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C11",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."STK_MOVEOUT_C12",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N1",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N2",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N3",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N4",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N5",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N6",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N7",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N8",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N9",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N10",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N11",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."STK_MOVEOUT_N12",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L1",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L2",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L3",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L4",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L5",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L6",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L7",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L8",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L9",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L10",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L11",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."STK_MOVEOUT_L12",
    "STK_STOCK3"."STK_USRCHAR12",
    "STK_LOCATION"."LOC_CODE",
    "STK_LOCATION"."LOC_PHYSICAL",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."Total_NY",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."Total_CY",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."Total_LY",
    "STK_STOCK3"."STK_USRFLAG8",
    "STK_STOCK"."STK_EC_SUP_UNIT",
    "STK_STOCK"."STK_PHYSICAL",
    "STK_STOCK"."STK_ORDER_IN",
    "STK_STOCK3"."STK_USRFLAG3",
    "STK_STOCK3"."STK_USRCHAR2",
    "STK_LOCATION2"."LOC_USERDATE1",
    "STK_STOCK"."STK_EC_KILOS",
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."Expr1",
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."Expr1",
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."Expr1"
FROM
    (
        (
            (
                (
                    (
                        "VJSCL"."dbo"."STK_STOCK3" "STK_STOCK3"
                        INNER JOIN "VJSCL"."dbo"."STK_STOCK" "STK_STOCK" ON "STK_STOCK3"."STKCODE3" = "STK_STOCK"."STKCODE"
                    )
                    inner JOIN "VJSCL"."dbo"."VJSCL_STK_MOVEMENTS_NY_CasesUnit" "VJSCL_STK_MOVEMENTS_NY_CasesUnit" ON "STK_STOCK"."STKCODE" = "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."SM_STOCK_CODE"
                )
                INNER JOIN "VJSCL"."dbo"."STK_LOCATION" "STK_LOCATION" ON "STK_STOCK"."STKCODE" = "STK_LOCATION"."LOC_STOCK_CODE"
            )
            inner JOIN "VJSCL"."dbo"."VJSCL_STK_MOVEMENTS_CY_CasesUnit" "VJSCL_STK_MOVEMENTS_CY_CasesUnit" ON "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."SM_STOCK_CODE" = "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."SM_STOCK_CODE"
        )
        inner JOIN "VJSCL"."dbo"."VJSCL_STK_MOVEMENTS_LY_CasesUnit" "VJSCL_STK_MOVEMENTS_LY_CasesUnit" ON "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."SM_STOCK_CODE" = "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."SM_STOCK_CODE"
    )
    INNER JOIN "VJSCL"."dbo"."STK_LOCATION2" "STK_LOCATION2" ON (
        "STK_LOCATION"."LOC_CODE" = "STK_LOCATION2"."LOC_CODE2"
    ) AND
    (
        "STK_LOCATION"."LOC_STOCK_CODE" = "STK_LOCATION2"."LOC_STOCKCODE2"
    )
WHERE
    NOT (
        "STK_STOCK"."STK_SORT_KEY1" = '30 .EUC ADVERTISING' OR
        "STK_STOCK"."STK_SORT_KEY1" = '30 .NIV ADVERTISING'
    ) AND
    "STK_STOCK3"."STK_USRFLAG3" = 0 AND
    "STK_STOCK3"."STK_USRCHAR2" <> 'OTHERS DIV' AND
    "VJSCL_STK_MOVEMENTS_CY_CasesUnit"."Expr1" IS NOT NULL AND
    "VJSCL_STK_MOVEMENTS_LY_CasesUnit"."Expr1" IS NOT NULL AND
    "VJSCL_STK_MOVEMENTS_NY_CasesUnit"."Expr1" IS NOT NULL
    -- and stkcode like '30niv_84155pr'
ORDER BY
    "STK_STOCK"."STK_SORT_KEY",
    "STK_STOCK"."STK_SORT_KEY1",
    "STK_STOCK"."STKCODE",
    "STK_LOCATION"."LOC_CODE"