SELECT AC.CUCODE AS 'Customer Code', AC.CUNAME AS 'Customer Name',  AD.AD_DELIVERY_ROUTE AS 'Day', AD.AD_ADDRESS, AD.AD_ADDRESS_USER1, AD.AD_ADDRESS_USER2
FROM SL_ADDRESSES AD
INNER JOIN SL_ACCOUNTS AC ON AD.AD_ACC_CODE=AC.CUCODE
WHERE AC.CU_DO_NOT_USE = 0 AND (AD_DEL_ADDRESS = 1 OR AD_DEL_ADDRESS_2 = 1) AND AD.AD_DO_NOT_USE = 0
ORDER BY 2