SELECT [SupStatus]
      ,[SupCode]
      ,[SupName]
      ,[SupTaxNo]
      ,[SupAddr1]
      ,[SupAddr2]
      ,[SupAddrTown]
      ,[SupAddrProv]
      ,[SupAddrPC]
      ,[SupAddrCountry]
      ,[SupTel]
      ,[SupMobile]
      ,[SupEMail]
      ,[SupWWW]
      ,[SupContTitle]
      ,[SupContName]
      ,[SupContSurname]
      ,[SupCreditDays]
      ,[SupNominalAcc]
      ,[SupNominalDiscAcc]
  FROM [IBS004].[dbo].[Suppl]
  order by SupCode;



SELECT [Ledger]
      ,[CSCode]
      ,[CDUID]
      ,[CDParentUID]
      ,[CDTypeCategoryID]
      ,[CDTypeDesc]
      ,[CDDetails]
      ,[CDOrder]
      ,[CDLastModified]
      ,[CDUserID]
      ,[CDWorkstationID]
      ,[rn]
  FROM [IBS004].[dbo].[vCSFirstIBAN]
  order by CSCode;