SELECT
	STKCODE AS 'Inventory ID',
	STKNAME AS 'Description',
	STK_SORT_KEY1 AS 'Category',
	STK_SORT_KEY AS 'Brand',
	CASE
		WHEN V.VAT_RATE = 0 THEN 'RE'
		WHEN V.VAT_RATE = 5 THEN 'RR'
		WHEN V.VAT_RATE = 18 THEN 'RF'
	END AS 'Tax Category',
	CASE
		WHEN S3.STK_USRFLAG8 = 1 THEN 'Case'
		ELSE 'Unit'
	END AS 'Sales UOM',
	CASE
		WHEN S3.STK_USRFLAG8 = 1 THEN S.STK_EC_SUP_UNIT
		ELSE 1
	END AS 'Sales UOM Conversion to Base (Multiply)',
	CASE
		WHEN S.STK_EC_SUP_UNIT IS NULL OR
		S.STK_EC_SUP_UNIT = 0 THEN 1
		ELSE S.STK_EC_SUP_UNIT
	END AS 'Units per Case',
	CASE
		WHEN S3.STK_USRNUM6 = 0 THEN 1
		ELSE S3.STK_USRNUM6
	END AS 'Units per Pallet',
	S.STK_COSTPRICE AS 'Last Cost',
	S.STK_BASEPRICE AS 'Default Price',
	S2.STK_SELLPRICE10 AS 'RRP (incl. VAT)',
	CASE
		WHEN S.STK_S_WGHT_NAME = 'KG' THEN 'KG'
		ELSE ''
	END AS 'Weight UOM',
	CASE
		WHEN S.STK_S_WGHT_NAME = 'L' THEN S.STK_S_WEIGHT
		ELSE ''
	END AS 'Volume',
	CASE
		WHEN S.STK_S_WGHT_NAME = 'L' THEN 'L'
		ELSE ''
	END AS 'Volume UOM',
	CASE
		WHEN S.STK_S_WGHT_NAME = 'KG' THEN S.STK_S_WEIGHT
		ELSE ''
	END AS 'Content Weight',
	S3.STK_USRNUM8 AS 'Content Volume',
	S3.STK_USRNUM7 AS 'Units per Layer',
	CASE
		WHEN S3.STK_USRNUM7 = 0 OR
		S3.STK_USRNUM6 = 0 THEN 0
		ELSE S3.STK_USRNUM6 / S3.STK_USRNUM7
	END AS 'Pallet Layers',
	--NOT INCLUDED--
	S.STK_SORT_KEY2 AS 'Type',
	S.STK_SORT_KEY3 AS 'Supplier',
	S.STK_NOTES AS 'Notes',
	S.STK_BARCODE AS 'Barcode',
	S.STK_EC_COM_CODE AS 'Commodity Code',
	S.STK_EC_KILOS AS 'Expiry Days Alarm',
	--CUSTOM FIELDS--
	S3.STK_USRFLAG1 AS 'Do Not Load',
	S3.STK_USRCHAR2 AS 'Company Division',
	S3.STK_USRCHAR5 AS 'Barcode 2',
	S3.STK_USRNUM1 AS 'PO Min Qty',
	S3.STK_USRNUM2 AS 'Commission Rate %',
	S3.STK_USRFLAG2 AS 'Order Process',
	S3.STK_USRCHAR12 AS 'Order Shelf Life',
	S3.STK_USRCHAR13 AS 'Sales Min Ord Qty',
	S3.STK_USRFLAG4 AS 'Pick List Large Bag',
	S3.STK_USRFLAG6 AS 'Exclude MHV Report',
	S3.STK_USRCHAR6 AS 'Brand Category',
	S3.STK_USRFLAG7 AS 'Orijen Special Breed',
	S3.STK_USRFLAG8 AS 'Sell Only In Cases',
	S3.STK_USRCHAR7 AS 'Barcode Outer Case',
	ISNULL(S3.STK_USRCHAR14, '') AS 'Dimensions',
	S3.STK_USRNUM4 AS 'Min Stock Coverage',
	S3.STK_USRNUM5 AS 'Max Stock Coverage',
	ISNULL(S3.STK_USRCHAR16, '') AS 'Executive',
	ISNULL(S3.STK_USRCHAR17, '') AS 'Champion Category',
	S3.STK_USRNUM9 AS 'Weight / Pallet',
	ISNULL(S3.STK_USRCHAR18, '') AS 'Categ Manager'
FROM
	STK_STOCK S
	INNER JOIN STK_STOCK3 S3 ON S.STKCODE = S3.STKCODE3
	INNER JOIN STK_STOCK_2 S2 ON S.STKCODE = S2.STKCODE2
	INNER JOIN SL_ANALYSIS SL ON S2.STK_SANALYSIS1 = SL.SACODE
	INNER JOIN SYS_VATCONTROL V ON SL.SAVATCODE = V.VAT_CODE
	INNER JOIN (
		SELECT DISTINCT
			LOC_STOCKCODE2,
			LOC_USERFLAG1,
			LOC_USERFLAG2
		FROM
			STK_LOCATION2
	) L ON S.STKCODE = L.LOC_STOCKCODE2
WHERE
	s.STK_DO_NOT_USE = 0 AND
	S3.STK_USRFLAG3 = 0 AND
	STK_SORT_KEY IN (
		'30 NIVEA',
		'30 ELASTOPLAST',
		'30 DEMAKUP',
		'30 FIOCCO',
		'30 NUVENIA',
		'30 TEMPO'
	)
ORDER BY
	stk_sort_key,
	stkcode;