declare @Customer varchar(100) = 'VJ SALOMONE AMPLECARE LTD';

WITH WorkingDaysCTE AS (
    SELECT 
        CAST(WorkingDays AS FLOAT) / CAST(WorkedDays AS FLOAT) AS WorkedDaysRatio
    FROM 
        (SELECT COUNT(fulldate) AS WorkingDays
         FROM [Spot].[dbo].[calendarTbl]
         WHERE isbusday = 1 AND YEAR(fulldate) = YEAR(GETDATE()) AND holiday = 0) AS TotalWorkingDays,
        (SELECT COUNT(fulldate) AS WorkedDays
         FROM [Spot].[dbo].[calendarTbl]
         WHERE isbusday = 1 AND YEAR(fulldate) = YEAR(GETDATE()) AND holiday = 0 AND 
               fulldate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) AND GETDATE()) AS TotalWorkedDaysTillDate
)
SELECT 
Customer,
DeliveryAddress,
CustCategory,
Division,
Brand,
[Pet/PersC/Food],
[Det/HouseH/Niv],
CASE WHEN Sales_2Y IS NULL THEN 0 ELSE Sales_2Y END AS Sales_2Y,
CASE WHEN Sales_LY IS NULL THEN 0 ELSE Sales_LY END AS Sales_LY,
CASE WHEN Qty_LY IS NULL THEN 0 ELSE Qty_LY END AS Qty_LY,
CASE WHEN (Sales_2Y IS NULL OR Sales_2Y=0) AND (Sales_LY IS NOT NULL OR Sales_LY!=0) THEN 100
	ELSE CASE WHEN (Sales_LY IS NULL OR Sales_LY=0) THEN 0
		ELSE (Sales_LY-Sales_2Y)/Sales_2Y END END AS 'Growth_2Y_LY',
CASE WHEN (Sales_2Y IS NULL OR Sales_2Y=0) AND (Sales_LY IS NOT NULL OR Sales_LY!=0) THEN Sales_LY
	ELSE CASE WHEN (Sales_LY IS NULL OR Sales_LY=0) THEN 0
		ELSE (Sales_LY-Sales_2Y) END END AS 'Diff_2Y_LY',
CASE WHEN Sales_LYTD IS NULL THEN 0 ELSE Sales_LYTD END AS Sales_LYTD,
CASE WHEN Sales_YTD IS NULL THEN 0 ELSE Sales_YTD END AS Sales_YTD,
CASE WHEN Qty_LYTD IS NULL THEN 0 ELSE Qty_LYTD END AS Qty_LYTD,
CASE WHEN Qty_YTD IS NULL THEN 0 ELSE Qty_YTD END AS Qty_YTD,
CASE WHEN (Sales_LYTD IS NULL OR Sales_LYTD=0) AND (Sales_YTD IS NOT NULL OR Sales_YTD!=0) THEN 100
	ELSE CASE WHEN (Sales_YTD IS NULL OR Sales_YTD=0) THEN 0
		ELSE (Sales_YTD-Sales_LYTD)/Sales_LYTD END END AS 'Growth_YTD_LYTD',
CASE WHEN (Sales_LYTD IS NULL OR Sales_LYTD=0) AND (Sales_YTD IS NOT NULL OR Sales_YTD!=0) THEN Sales_LY
	ELSE CASE WHEN (Sales_YTD IS NULL OR Sales_YTD=0) THEN 0
		ELSE (Sales_YTD-Sales_LYTD) END END AS 'Diff_YTD_LYTD',
CASE WHEN Sales_YTD IS NULL THEN 0 ELSE Sales_YTD * wd.WorkedDaysRatio END AS 'FCST Y',
CASE WHEN Qty_YTD IS NULL THEN 0 ELSE Qty_YTD * wd.WorkedDaysRatio END AS 'FCST Y Qty',
CASE WHEN GrossProfit IS NULL THEN 0 ELSE GrossProfit END AS 'GrossProfit',
CASE WHEN [VJ % Margin] IS NULL THEN 0 ELSE GrossProfit END AS 'VJ % Margin'
FROM (SELECT 
MIN(A.CUNAME) AS Customer,
AD.AD_ADDRESS AS DeliveryAddress,
A.CUSORT AS CustCategory,
S3.STK_USRCHAR2 AS Division,
S.STK_SORT_KEY AS Brand,
A2.CU_USRCHAR9 AS 'Pet/PersC/Food',
A2.CU_USRCHAR11 AS 'Det/HouseH/Niv',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE())-2 THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_NETT ELSE DET_NETT*-1 END END) AS 'Sales_2Y',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE())-1 THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_NETT ELSE DET_NETT*-1 END END) AS 'Sales_LY',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE())-1 AND DET_DATE<=DATEADD(YEAR,-1,GETDATE()) THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_NETT ELSE DET_NETT*-1 END END) AS 'Sales_LYTD',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE()) THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_NETT ELSE DET_NETT*-1 END END) AS 'Sales_YTD',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE()) THEN 
		CASE WHEN D.DET_TYPE = 'CRN' THEN D.DET_NETT*-1 ELSE D.DET_NETT END - 
		CASE WHEN D.DET_TYPE = 'CRN' THEN D.DET_COSTPRICE*-1 * ((D.DET_QUANTITY*-1)*(D.DET_UNIT_QTY*-1)) 
		ELSE D.DET_COSTPRICE * (D.DET_QUANTITY*D.DET_UNIT_QTY) END END) AS 'GrossProfit',
CASE 
  WHEN SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE()) 
           THEN CASE WHEN D.DET_TYPE='INV' THEN DET_NETT ELSE DET_NETT*-1 END 
       END) = 0 
  THEN 0
  ELSE
    SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE()) THEN 
          (CASE WHEN D.DET_TYPE = 'CRN' THEN D.DET_NETT*-1 ELSE D.DET_NETT END) - 
          (CASE WHEN D.DET_TYPE = 'CRN' 
                THEN D.DET_COSTPRICE*-1 * ((D.DET_QUANTITY*-1)*(D.DET_UNIT_QTY*-1)) 
                ELSE D.DET_COSTPRICE * (D.DET_QUANTITY*D.DET_UNIT_QTY) 
           END)
        END)
    /
    SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE()) 
          THEN CASE WHEN D.DET_TYPE='INV' THEN DET_NETT ELSE DET_NETT*-1 END 
        END)
END AS 'VJ % Margin',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE())-1 THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_QUANTITY ELSE DET_QUANTITY*-1 END END) AS 'Qty_LY',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE())-1 AND DET_DATE<=DATEADD(YEAR,-1,GETDATE()) THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_QUANTITY ELSE DET_QUANTITY*-1 END END) AS 'Qty_LYTD',
SUM(CASE WHEN YEAR(DET_DATE)=YEAR(GETDATE()) THEN 
		CASE WHEN D.DET_TYPE='INV' THEN DET_QUANTITY ELSE DET_QUANTITY*-1 END END) AS 'Qty_YTD'
FROM SL_PL_NL_DETAIL D
INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE=S.STKCODE
INNER JOIN STK_STOCK3 S3 ON D.DET_STOCK_CODE=S3.STKCODE3
INNER JOIN SL_ACCOUNTS A ON D.DET_ACCOUNT=A.CUCODE
INNER JOIN SL_ACCOUNTS2 A2 ON A.CUCODE=A2.CUCODE2
INNER JOIN ORD_DETAIL OD ON OD.OD_PRIMARY=D.DET_ORDER_LINK
INNER JOIN ORD_HEADER OH ON OD.OD_ORDER_NUMBER=OH.OH_ORDER_NUMBER
INNER JOIN SL_ADDRESSES AD ON A.CUCODE=AD.AD_ACC_CODE AND OH.OH_DEL_ADD=AD.AD_CODE
WHERE D.DET_ORIGIN='SO' AND D.DET_TYPE IN ('INV','CRN')
AND YEAR(DET_DATE)>=YEAR(GETDATE())-2
AND A.CUNAME IN ('VJ SALOMONE AMPLECARE LTD') AND CUNAME +' | ' + AD_ADDRESS IN (
    SELECT DISTINCT CUNAME +' | ' + AD_ADDRESS AS CustDelivery
FROM SL_ADDRESSES AD
INNER JOIN SL_ACCOUNTS A ON AD.AD_ACC_CODE=A.CUCODE
WHERE 
-- AD_DEL_ADDRESS_2=1 AND 
CUNAME IN ('VJ SALOMONE AMPLECARE LTD')
) 
AND S3.STK_USRCHAR2 IN ('MAIN DIV','PET DIV','OTHERS DIV')
AND S.STK_SORT_KEY NOT IN ('30 NIVEA ADVERTISING','30 PET FOOD','30 BOY')
GROUP BY S3.STK_USRCHAR2, A.CUSORT, S.STK_SORT_KEY, A2.CU_USRCHAR9, A2.CU_USRCHAR11, AD.AD_ADDRESS
) T
CROSS JOIN WorkingDaysCTE wd
-- WHERE Division IN (@Division)
WHERE Division IN (
    SELECT DISTINCT STK_USRCHAR2 As Division
FROM STK_STOCK3
WHERE STK_USRCHAR2 IN ('MAIN DIV','PET DIV','OTHERS DIV')
)


