WITH TOTQTY AS (
SELECT LOC_STOCK_CODE AS STKCODE, SUM(LOC_PHYSICAL) AS QTY, MAX(L2.LOC_USERTEXT1) AS MARS
FROM STK_LOCATION  L
INNER JOIN STK_LOCATION2 L2 ON L.LOC_CONCATCODE=L2.LOC_CONCATCODE2
LEFT JOIN (SELECT LOC_STOCKCODE2,MAX(LOC_USERDATE1) AS MAXEXPIR 
	FROM STK_LOCATION2 
    WHERE LOC_CODE2 NOT LIKE 'WHQ%' 
    GROUP BY LOC_STOCKCODE2) 
	M ON L2.LOC_STOCKCODE2=M.LOC_STOCKCODE2 AND L2.LOC_USERDATE1=M.MAXEXPIR
INNER JOIN STK_STOCK S ON L.LOC_STOCK_CODE=S.STKCODE
WHERE S.STK_SORT_KEY='50NOVARTIS' 
AND L.LOC_USERSORT1 != 'WHQ'
GROUP BY LOC_STOCK_CODE
--HAVING SUM(LOC_PHYSICAL)>0

union 

SELECT LOC_STOCK_CODE AS STKCODE, 0 AS QTY, MAX(L2.LOC_USERTEXT1) AS MARS
FROM STK_LOCATION  L
INNER JOIN STK_LOCATION2 L2 ON L.LOC_CONCATCODE=L2.LOC_CONCATCODE2
INNER JOIN STK_STOCK S ON L.LOC_STOCK_CODE=S.STKCODE
WHERE S.STK_SORT_KEY='50NOVARTIS' 
AND L.LOC_USERSORT1 = 'WHQ'
GROUP BY LOC_STOCK_CODE

),

MINMRS AS (
SELECT L2.LOC_STOCKCODE2 AS STKCODE, MIN(L2.LOC_USERTEXT1) AS OLDMARS, SUM(L.LOC_PHYSICAL) AS OLDPHYS
FROM STK_LOCATION2 L2
INNER JOIN (SELECT XL2.LOC_STOCKCODE2,MIN(XL2.LOC_USERTEXT1) AS MINMARS
	FROM STK_LOCATION2 XL2 
	INNER JOIN STK_LOCATION XL ON XL.LOC_CONCATCODE=XL2.LOC_CONCATCODE2
	WHERE XL.LOC_CODE NOT LIKE 'WHQ%' AND XL.LOC_PHYSICAL>0
	GROUP BY XL2.LOC_STOCKCODE2
	HAVING MIN(XL2.LOC_USERTEXT1)!=MAX(XL2.LOC_USERTEXT1))
	M ON L2.LOC_STOCKCODE2=M.LOC_STOCKCODE2 AND L2.LOC_USERTEXT1=M.MINMARS
INNER JOIN STK_LOCATION L ON L.LOC_CONCATCODE=L2.LOC_CONCATCODE2
WHERE LOC_CODE NOT LIKE 'WHQ%' AND L.LOC_PHYSICAL>0
GROUP BY L2.LOC_STOCKCODE2
),

SALES AS (
SELECT D.DET_STOCK_CODE AS STKCODE, 
CAST(SUM(CASE D.DET_TYPE WHEN 'INV' THEN D.DET_QUANTITY WHEN 'CRN' THEN D.DET_QUANTITY*-1 ELSE 0 END)/4 AS DECIMAL(10,2)) AS AVGSALES
FROM SL_PL_NL_DETAIL D
INNER JOIN STK_STOCK S ON D.DET_STOCK_CODE=S.STKCODE
WHERE DET_DATE BETWEEN DATEADD(month,DATEDIFF(month, 0, GETDATE())-4,0) AND DATEADD(month,DATEDIFF(month, 0, GETDATE()),0)-1
AND S.STK_SORT_KEY='50NOVARTIS'  AND DET_ORIGIN='SO'
GROUP BY D.DET_STOCK_CODE
),

WHQ AS (
SELECT LOC_STOCK_CODE AS STKCODE, SUM(LOC_PHYSICAL) AS QAQTY
FROM STK_LOCATION  L
INNER JOIN STK_STOCK S ON L.LOC_STOCK_CODE=S.STKCODE
WHERE S.STK_SORT_KEY='50NOVARTIS' AND L.LOC_USERSORT1 = 'WHQ'
GROUP BY LOC_STOCK_CODE
HAVING SUM(LOC_PHYSICAL)>0
)

SELECT CASE WHEN S.STKNAME LIKE '%COMPASSION%' THEN 'NA' ELSE
CASE STK_SORT_KEY3 WHEN '50STOCK' THEN '100246-'+T.MARS 
WHEN '50TENDER' THEN '100501-'+T.MARS END END AS CUST_MARS, T.MARS, S.STKCODE, S.STKNAME AS [Description], 
CASE WHEN SL.AVGSALES IS NULL THEN 0 ELSE SL.AVGSALES END AS AvgMonthlySales,
T.QTY AS StockInDistributorWH,
CAST(CASE WHEN (SL.AVGSALES IS NULL OR SL.AVGSALES = 0) AND T.QTY = 0 THEN 0 WHEN (SL.AVGSALES IS NULL OR SL.AVGSALES = 0) AND T.QTY != 0 THEN 100 ELSE T.QTY/SL.AVGSALES END AS DECIMAL(10,2)) AS MFC,
CASE WHEN WHQ.QAQTY IS NULL THEN 0 ELSE WHQ.QAQTY END AS StockAwaitingQARelease,
CAST(CASE WHEN (SL.AVGSALES IS NULL OR SL.AVGSALES = 0) AND (T.QTY+(CASE WHEN WHQ.QAQTY IS NULL THEN 0 ELSE WHQ.QAQTY END))  = 0 THEN 0 
		  WHEN (SL.AVGSALES IS NULL OR SL.AVGSALES = 0) AND (T.QTY+(CASE WHEN WHQ.QAQTY IS NULL THEN 0 ELSE WHQ.QAQTY END)) != 0 THEN 100 
		  ELSE (T.QTY+(CASE WHEN WHQ.QAQTY IS NULL THEN 0 ELSE WHQ.QAQTY END))/SL.AVGSALES END AS DECIMAL(10,2)) AS MFC_QA,
OLDMARS, OLDPHYS AS OldMarsQty
FROM STK_STOCK S
INNER JOIN TOTQTY T ON S.STKCODE=T.STKCODE
LEFT JOIN SALES SL ON S.STKCODE=SL.STKCODE
left JOIN WHQ ON S.STKCODE=WHQ.STKCODE
LEFT JOIN MINMRS ON S.STKCODE=MINMRS.STKCODE
WHERE S.STK_SORT_KEY='50NOVARTIS' AND T.MARS != '' AND S.STK_DO_NOT_USE = 0